# .github/workflows/ci-pipeline.yml
name: CI Pipeline

on:
  workflow_dispatch:
    inputs:
      java_version:
        description: 'Java version'
        required: true
        default: '21'
      run_test:
        description: 'Run test stage'
        required: false
        default: false
        type: boolean
      run_sonarcloud:
        description: 'Run SonarCloud analysis'
        required: false
        default: false
        type: boolean
      run_codeql:
        description: 'Run CodeQL analysis'
        required: false
        default: false
        type: boolean
      run_qodana:
        description: 'Run Qodana analysis'
        required: false
        default: false
        type: boolean
      run_docker:
        description: 'Build and push Docker image'
        required: false
        default: false
        type: boolean
      run_maven_publish:
        description: 'Publish Maven release'
        required: false
        default: false
        type: boolean

jobs:
  CI:
    uses: e-CODEX/workflows/.github/workflows/ctp-automated-testing.yml@ctp-automated-testing
    with:
      java_version:      ${{ github.event.inputs.java_version || '21' }}
      run_test:          ${{ fromJSON(github.event.inputs.run_test || 'false') }}
      run_sonarcloud:    ${{ fromJSON(github.event.inputs.run_sonarcloud || 'false') }}
      run_codeql:        ${{ fromJSON(github.event.inputs.run_codeql || 'false') }}
      run_qodana:        ${{ fromJSON(github.event.inputs.run_qodana || 'false') }}
      run_docker:        ${{ fromJSON(github.event.inputs.run_docker || 'false') }}
      run_maven_publish: ${{ fromJSON(github.event.inputs.run_maven_publish || 'false') }}
    secrets: inherit

  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug info
        run: |
          echo "Run Tests: ${{ fromJSON(github.event.inputs.run_test || 'false') }}"
          echo "Run SonarCloud: ${{ fromJSON(github.event.inputs.run_sonarcloud || 'false') }}"
          echo "Run CodeQL: ${{ fromJSON(github.event.inputs.run_codeql || 'false') }}"
          echo "Run Qodana: ${{ fromJSON(github.event.inputs.run_qodana || 'false') }}"
          echo "Run Docker: ${{ fromJSON(github.event.inputs.run_docker || 'false') }}"
          echo "Run Maven Publish: ${{ fromJSON(github.event.inputs.run_maven_publish || 'false') }}"
          echo "Java Version: ${{ github.event.inputs.java_version || '21' }}"
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
          echo "GITHUB_SHA=$GITHUB_SHA"
